/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'title' : IDL.Text,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'title' : IDL.Text,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };